import App from '../../components/app/app'
import { AuthProvider } from '../../context/authContext'
import './globals.css'
import { Inter } from 'next/font/google'
import { GoogleOAuthProvider } from '@react-oauth/google';
import { NotificationProvider } from '../../context/notifyContext';
import axios from 'axios';
import { ACCESS_TOKEN } from '../../infra/const';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}




export default function RootLayout({children,}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NotificationProvider>
          <AuthProvider>
            <App>
              {children}
            </App>
          </AuthProvider>
        </NotificationProvider>
      </body>
    </html>
  )
}
